volumes:
  prs_data:

services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: django
    volumes:
      - prs_data:/var/lib/postgresql/data
    container_name: pr_postgres_db
  backend:
    build: ./pull_request_service/
    depends_on:
      - db
    container_name: pr_api
    ports:
      - "8080:8080"